version: '3'
services:
  ipfs:
    container_name: "ipfs"
    expose:
    - 4001
    - 8080
    ports:
    - 4001:4001
    - 5001:5001
    - 8080:8080
    image: ipfs/go-ipfs
    volumes:
      - /tmp/ipfs/:/data/ipfs/
  mongo:
    image: mongo
    volumes:
      - ./tmp/database:/var/lib/mysql
    container_name: "mongo"
    expose:
    - 27019
    ports:
    - 27019:27017
  web:
    environment:
      - IPFSPICS_DB=${IPFSPICS_DB}
    container_name: "web"
    build: .
    expose:
    - 5000
    ports:
    - 5000:80
    volumes:
    - logvolume01:/var/log
    - ./app:/var/www/html/app
    links:
      - ipfs
      - mongo
volumes:
  logvolume01: {}

